export const examToLanguage = {
  TOEIC: "영어",
  "TOEIC(Speaking)": "영어",
  "TOEIC Speaking and Writing Tests": "영어",
  "TOEFL(PBT)": "영어",
  "TOEFL(CBT)": "영어",
  "TOEFL(iBT)": "영어",
  TEPS: "영어",
  IELTS: "영어",
  "G-TELP(GLT)": "영어",
  "G-TELP(GST)": "영어",
  SLEP: "영어",
  GRE: "영어",
  GMAT: "영어",
  PELT: "영어",
  OPIc: "러시아어",
  "OPIc Writing": "영어",
  "FLEX 영어": "영어",
  JPT: "일본어",
  JLPT: "일본어",
  新JLPT: "일본어",
  JTRA: "일본어",
  NPT: "일본어",
  SJPT: "일본어",
  OPIC: "일본어",
  "FLEX 일본어": "일본어",
  HSK: "중국어",
  新HSK: "중국어",
  HSK회화: "중국어",
  新HSK회화: "중국어",
  TSC: "중국어",
  BCT: "중국어",
  CPT: "중국어",
  "新BCT(A)": "중국어",
  "新BCT(B)": "중국어",
  "新BCT(Speaking)": "중국어",
  "FLEX 중국어": "중국어",
  ZDAF: "독일어",
  ZMP: "독일어",
  GDS: "독일어",
  KDS: "독일어",
  DSH: "독일어",
  "FLEX 독일어": "독일어",
  PWD: "독일어",
  SD1: "독일어",
  SD2: "독일어",
  "SNULT 독일어": "독일어",
  "TCT 번역능력인정시험 독일어": "독일어",
  TestDaF: "독일어",
  ZD: "독일어",
  ZOP: "독일어",
  "관광통역안내사 독일어": "독일어",
  DELF: "프랑스어",
  DALF: "프랑스어",
  "FLEX 프랑스어": "프랑스어",
  직접입력: "한국어",
  DELE: "스페인어",
  "FLEX 스페인어": "스페인어",
  TORFL: "러시아어",
  "FLEX 러시아어": "러시아어",
  국어능력인증시험: "한국어",
  "한국어 교원자격증": "한국어",
  "KBS 한국어능력시험": "한국어",
  TOPIK: "한국어"
};
